Handle responses with 0 or missing Content-Length
Previously utils.py:parse_result failed with:

> TypeError: Cannot auto-detect response type due to missing
> Content-Type header.

Observed these symptoms with 18.06.0-ce, build 0ffa825 when calling
containers.py:put_archive.

Also fix typo in error message.  Fixes #237.